### PR TITLE
Attempt to fix #80

### LINKED ISSUE #80: Does not work in ionic cordova emulate ios --livereload
screen shot 2017-07-18 at 1 13 07 pm

### PR DESCRIPTION
**Pull request by leoiii12**

### CODE REVIEW

File: src/providers/image-loader.ts [hunk 1]
```diff
@@ -67,11 +69,28 @@ export class ImageLoader {
...
+    if (this.platform.is('ios') && (<any>window).webkit && (<any>window).webkit.messageHandlers) {
+      return true;
+    }
+
+    return false;
   }
 
   private get isIonicWKWebView(): boolean {
-    return this.isWKWebView && location.host === 'localhost:8080';
+    if (this.isWKWebView) {
```
Comment (ihadeed) [inline src/providers/image-loader.ts]: I'd rather make this method do this:
```ts
return this.isWKWebView && (location.host === 'localhost:8080'  || (<any>window).LiveReload);
```

Then we can remove `declare var LiveReload;`

File: src/providers/image-loader.ts [hunk 2]
```diff
@@ -67,11 +69,28 @@ export class ImageLoader {
   }
 
   private get isWKWebView(): boolean {
-    return this.platform.is('ios') && (<any>window).webkit;
+    if (this.platform.is('ios') && (<any>window).webkit && (<any>window).webkit.messageHandlers) {
```
Comment (ihadeed) [inline src/providers/image-loader.ts]: Out of curiosity, why do we need `webkit.messageHandlers` ?

Comment (leoiii12) [inline src/providers/image-loader.ts]: I don't know whether it is necessary or not. When I was inspecting the issue with Livereload, I saw people are using with **webkit.messageHandlers**.
https://stackoverflow.com/questions/28795476/detect-if-page-is-loaded-inside-wkwebview-in-javascript
Therefore, I made this change.
